<a href="https://colab.research.google.com/github/LeraDoroshenko/mn/blob/main/%D0%94%D0%BE%D1%80%D0%BE%D1%88%D0%B5%D0%BD%D0%BA%D0%BE_%D0%BB%D0%B11_%D0%B29.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
numpy_version = np.__version__
print(f"NumPy version: {numpy_version}")

NumPy version: 1.26.4


***1. Створіть одновимірний масив (вектор) з числами Фібоначчі, де кожне число дорівнює сумі двох попередніх, та виведіть його значення.***

In [4]:
def array(n):
    arr = np.zeros(n, dtype=int)
    arr[0] = 0
    arr[1] = 1
    for i in range(2, n):
        arr[i] = arr[i-1] + arr[i-2]
    return arr

n = 10
arr = array(n)
print(arr)

[ 0  1  1  2  3  5  8 13 21 34]


***2. Створіть двовимірний масив (матрицю) розміром 3х3, заповніть його значеннями експонент n^2 для кожного натурального числа n, починаючи з 1, та виведіть його значення.***

In [5]:
matrix = np.zeros((3, 3), dtype=float)

n = 1
for i in range(3):
    for j in range(3):
        matrix[i, j] = np.exp(n**2)
        n += 1

print(matrix)

[[2.71828183e+00 5.45981500e+01 8.10308393e+03]
 [8.88611052e+06 7.20048993e+10 4.31123155e+15]
 [1.90734657e+21 6.23514908e+27 1.50609731e+35]]


***3. Створіть масив розміром 3х3, заповніть його випадковими дійсними числами від -1 до 1 та виведіть його значення.***

In [6]:
matrix = np.random.uniform(-1, 1, (3, 3))

print(matrix)

[[-0.03909575  0.32248177 -0.84771238]
 [ 0.81892803  0.32527471 -0.01684459]
 [-0.49499215  0.91182638  0.09465225]]


***4. Створіть масив розміром 3х3, заповніть його випадковми дійсними числами в діапазоні від 0 до 1 та знайдіть середнє геометричне всіх елементів.***

In [7]:
from scipy.stats import gmean

matrix = np.random.uniform(0, 1, (3, 3))

print("Matrix:")
print(matrix)

geom = gmean(matrix.flatten())

print("\nGeom:")
print(geom)

Matrix:
[[0.58886224 0.35173307 0.51674803]
 [0.55350179 0.88417227 0.15218397]
 [0.87145314 0.84616298 0.35116619]]

Geom:
0.5030810099725301


***5. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими дійсними числами від -5 до 5 та виконайте на них поелементні оперції додавання, віднімання та множення.***

In [8]:
array1 = np.random.uniform(-5, 5, 6)
array2 = np.random.uniform(-5, 5, 6)

add = array1 + array2

sub = array1 - array2

mult = array1 * array2

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

print("\nAddition:")
print(add)
print("\nSubtraction:")
print(sub)
print("\nMultiplication:")
print(mult)

Array 1:
[-0.50696413  3.63983188 -3.35942772 -4.31885992 -0.30266433 -2.82063687]

Array 2:
[-3.74157199 -0.23719849  0.60011537  0.38278355 -0.47576241  4.7576954 ]

Addition:
[-4.24853612  3.40263339 -2.75931235 -3.93607637 -0.77842673  1.93705853]

Subtraction:
[ 3.23460785  3.87703037 -3.95954308 -4.70164348  0.17309808 -7.57833227]

Multiplication:
[  1.89684279  -0.86336263  -2.01604419  -1.65318855   0.14399631
 -13.41973107]


***6. Створіть дві матриці 5х5, заповніть їх довільними цілими числами від 1 до 10 та знайдіть їх добуток.***

In [9]:
matrix1 = np.random.randint(1, 11, (5, 5))
matrix2 = np.random.randint(1, 11, (5, 5))

product = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nMatrix Product:")
print(product)

Matrix 1:
[[ 9  5  6  7  2]
 [ 6  3  1  5  9]
 [ 7  2  1  9  7]
 [ 6  5  3  5 10]
 [ 2  9 10  3  2]]

Matrix 2:
[[10  4  2  8  7]
 [ 1  1  7  3  6]
 [ 3  3  6  8  5]
 [ 6  8  6  8  7]
 [ 9  8  1  3  7]]

Matrix Product:
[[173 131 133 197 186]
 [177 142  78 132 163]
 [192 161  95 163 178]
 [194 158 105 157 192]
 [ 95  87 147 153 153]]


***7. Створіть дві матриці розміром 3х2 та 2х4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.***

In [11]:
matrix1 = np.random.randint(1, 11, (3, 2))

matrix2 = np.random.randint(1, 11, (2, 4))

product = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nMatrix Product:")
print(product)

Matrix 1:
[[5 1]
 [9 5]
 [7 4]]

Matrix 2:
[[ 3 10  7 10]
 [10  4  3 10]]

Matrix Product:
[[ 25  54  38  60]
 [ 77 110  78 140]
 [ 61  86  61 110]]


***8. Створіть матрицю розміром 2х2, заповніть її випадковими цілими числами в діапазоні від 1 до 15 та знайдіть її обернену матрицю.***

In [12]:
matrix = np.random.randint(1, 16, (2, 2))

inverse_matrix = np.linalg.inv(matrix)

print("Matrix:")
print(matrix)

print("\nInverse Matrix:")
print(inverse_matrix)

Matrix:
[[ 2  1]
 [15  9]]

Inverse Matrix:
[[ 3.         -0.33333333]
 [-5.          0.66666667]]


***9. Створіть матрицю розміром 3х3, заповніть її випадковими цілими числами в діапазоні від 7 до 15 та транспонуйте її.***

In [13]:
matrix = np.random.randint(7, 16, (3, 3))

transposed_matrix = matrix.T

print("Matrix:")
print(matrix)

print("\nTransposed Matrix:")
print(transposed_matrix)

Matrix:
[[14 13  9]
 [13 14 13]
 [ 9  9  8]]

Transposed Matrix:
[[14 13  9]
 [13 14  9]
 [ 9 13  8]]


***10. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10 і знайдіть добуток матриці на вектор.***

In [14]:
matrix = np.random.uniform(0, 1, (3, 4))

vector = np.random.randint(1, 11, (4, 1))

product = np.dot(matrix, vector)

print("Matrix:")
print(matrix)

print("\nVector:")
print(vector)

print("\nProduct:")
print(product)

Matrix:
[[0.38876865 0.81639623 0.96654796 0.28225855]
 [0.70038398 0.54190155 0.61445544 0.99133059]
 [0.75288223 0.85135728 0.91363722 0.13622181]]

Vector:
[[ 9]
 [ 2]
 [ 1]
 [10]]

Product:
[[ 8.92084379]
 [17.91502027]
 [10.75450993]]


***11. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.***

In [15]:
matrix = np.random.uniform(0, 1, (2, 3))

vector = np.random.randint(1, 11, (3, 1))

product = np.dot(matrix, vector)

print("Matrix:")
print(matrix)

print("\nVector:")
print(vector)

print("\nProduct:")
print(product)

Matrix:
[[0.20885234 0.99550215 0.0047761 ]
 [0.20338089 0.74816073 0.01049132]]

Vector:
[[ 2]
 [ 2]
 [10]]

Product:
[[2.45646997]
 [2.00799639]]


***12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму всіх елементів обох матриць.***

In [16]:
matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))

sum_matrix1 = np.sum(matrix1)
sum_matrix2 = np.sum(matrix2)
total_sum = sum_matrix1 + sum_matrix2

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nSum 1:")
print(sum_matrix1)

print("\nSum 2:")
print(sum_matrix2)

print("\nTotal sum :")
print(total_sum)

Matrix 1:
[[ 4 10]
 [ 7  6]]

Matrix 2:
[[2 2]
 [6 7]]

Sum 1:
27

Sum 2:
17

Total sum :
44


***13. Створіть дві матриці розміром 10x10, заповніть їх випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть їх добуток.***

In [17]:
matrix1 = np.random.uniform(-2, 2, (10, 10))
matrix2 = np.random.uniform(-2, 2, (10, 10))

product = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nProduct:")
print(product)

Matrix 1:
[[-0.74243242  0.59212276  0.69992078 -0.11196011  0.52976237 -0.74576585
  -1.84596116 -1.10289567  0.11618285  1.94219874]
 [-0.21956155  0.47346213  1.45389148  1.06297861 -1.19817299  0.34019043
  -1.85413595  0.90769219  0.6200104   1.64611901]
 [ 1.53313775 -0.43560493  0.8068286   0.53143428  1.98095235  1.91754823
   0.23721427 -0.85975704 -1.20232252  0.91010181]
 [-1.13563679  1.09900946 -1.95147276 -0.26843498  1.83400249 -1.60436109
  -1.69124188 -0.85121126 -0.57170712 -1.35676632]
 [ 1.67755748  0.23153214 -1.22162056 -1.79208561  0.49697394 -0.13273595
   1.34970122  1.48237837 -1.56109764  0.37607805]
 [-1.10673665  1.22751999 -0.73101071  1.72361487  1.88897726 -0.93366569
   0.94973716 -0.34732389 -0.92321384  0.46508   ]
 [ 0.13905223  1.52456403  1.86438253 -0.20625096  0.6053932   1.03823682
   1.33613724  1.11376876  0.95394792  1.99758955]
 [ 0.92789863 -0.82530011  1.84553458  1.96143911  1.14675269 -1.17623601
  -0.99006396  0.39951527 -0.93771838 -0.

***14. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть середнє арифметичне значення елементів матриці.***

In [18]:
matrix = np.random.uniform(-1, 1, (3, 3))

mean_value = np.mean(matrix)

print("Matrix:")
print(matrix)

print("\nMean Value:")
print(mean_value)

Matrix:
[[ 0.32540801  0.26875659  0.5375618 ]
 [ 0.32873101 -0.69024144 -0.01829825]
 [-0.68346156 -0.67169277 -0.83503209]]

Mean Value:
-0.15980763412829316


***15. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму квадратів елементів кожного рядка матриці.***

In [19]:
matrix = np.random.uniform(0, 1, (3, 3))

sum_of_squares = np.sum(matrix**2, axis=1)

result_vector = sum_of_squares.reshape(-1, 1)

print("Matrix:")
print(matrix)

print("\nVector:")
print(result_vector)

Matrix:
[[0.50738489 0.45322813 0.93297482]
 [0.77055074 0.85614962 0.27818719]
 [0.10241539 0.72309468 0.46411574]]

Vector:
[[1.33329718]
 [1.40412874]
 [0.74875825]]
